### ISSUE TITLE
SOAP-imported enum breaks JSON.Serialize

### ISSUE THREAD

**Issue by MaxHorstmann** [kevin-montrose/Jil#101]
There's an enum...

    public enum CouponStatus
    {
        Unusable,
        Usable
    }

... imported via Service Reference from a SOAP-based WS (you probably know which one I'm talking about...). Now this...

    var data = new { prices = new[] { 1, 2, 3 }, CouponStatus.Unusable };
    var json = JSON.SerializeDynamic(data, Options.PrettyPrint);  // same with non-dynamic

throws up:

```
Object reference not set to an instance of an object.
   at Jil.Common.ExtensionMethods.JsonEscape(String str, Boolean jsonp) in c:\Users\kevin_000\Dropbox\jil\Jil\Common\ExtensionMethods.cs:line 848
   at Jil.Serialize.InlineSerializer`1.WriteContiguousEnumeration(Type enumType, Dictionary`2 values, Boolean popTextWriter) in c:\Users\kevin_000\Dropbox\jil\Jil\Serialize\InlineSerializer.cs:line 2959
   at Jil.Serialize.InlineSerializer`1.WriteEnum(Type enumType, Boolean popTextWriter) in c:\Users\kevin_000\Dropbox\jil\Jil\Serialize\InlineSerializer.cs:line 3176
   at Jil.Serialize.InlineSerializer`1.WriteMember(MemberInfo member, Local inLocal) in c:\Users\kevin_000\Dropbox\jil\Jil\Serialize\InlineSerializer.cs:line 482
   at Jil.Serialize.InlineSerializer`1.WriteObjectWithNullsWithoutConditionalSerialization(Type forType, Local inLocal, List`1 writeOrder) in c:\Users\kevin_000\Dropbox\jil\Jil\Serialize\InlineSerializer.cs:line 1321
   at Jil.Serialize.InlineSerializer`1.WriteObjectWithNulls(Type forType, Local inLocal) in c:\Users\kevin_000\Dropbox\jil\Jil\Serialize\InlineSerializer.cs:line 1239
   at Jil.Serialize.InlineSerializer`1.WriteObject(Type forType, Local inLocal) in c:\Users\kevin_000\Dropbox\jil\Jil\Serialize\InlineSerializer.cs:line 1339
   at Jil.Serialize.InlineSerializer`1.BuildObjectWithNewImpl() in c:\Users\kevin_000\Dropbox\jil\Jil\Serialize\InlineSerializer.cs:line 3294
   at Jil.Serialize.InlineSerializer`1.BuildObjectWithNewDelegate() in c:\Users\kevin_000\Dropbox\jil\Jil\Serialize\InlineSerializer.cs:line 3300
   at Jil.Serialize.InlineSerializer`1.Build() in c:\Users\kevin_000\Dropbox\jil\Jil\Serialize\InlineSerializer.cs:line 3541
   at Jil.Serialize.InlineSerializerHelper._BuildWithDynamism[BuildForType](Type optionsType, Boolean pretty, Boolean excludeNulls, Boolean jsonp, DateTimeFormat dateFormat, Boolean includeInherited) in c:\Users\kevin_000\Dropbox\jil\Jil\Serialize\InlineSerializer.cs:line 3635
```

**Comment by deanward81** [comment]
@kevin-montrose it's definitely related to `EnumMember`. This throws a NullReferenceException using 2.6.0:

	static void Main()
	{
		var dataSucceeds = new { CouponStatus.Unusable };
		JSON.Serialize(dataSucceeds);
		
		var dataFails = new { CouponStatusFail.Unusable };
		JSON.Serialize(dataFails); // throws null ref
	}

	[DataContract(Name = "CouponStatus", Namespace = "http://tempuri.org/")]
	public enum CouponStatusFail
	{
		[EnumMember]Unusable,
		[EnumMember]Usable,
	}
	
	public enum CouponStatus
	{
		Unusable,
		Usable,
	}

Fix looks to be as simple as changing:

    if (enumMember == null)

to

    if (enumMember = null || enumMember.Value == null)

at https://github.com/kevin-montrose/Jil/blob/master/Jil/Common/ExtensionMethods.cs#L144.

**Comment by deanward81** [comment]
Added PR https://github.com/kevin-montrose/Jil/pull/102

**Comment by kevin-montrose** [comment]
@MaxHorstmann is it possible for you confirm this fix ^ ?  Unlikely I'll get to a new Nuget push before next week.

**Comment by MaxHorstmann** [comment]
@kevin-montrose fix confirmed!
