### ISSUE TITLE
Issue for Datetime offset value not deserialized

### ISSUE THREAD

**Issue by ravi032** [kevin-montrose/Jil#113]
I have a class which has property having datetimeoffset datatype. Kindly provide some solution.

class Employee
{
public System.DateTimeOffset joiningdate { get; set; }
}

Below line of code throws exception ->
Employee obj = JSON.Deserialize<Employee >("{"joiningdate ":"2015-02-26T11:29:36.000Z"}");

Exception: Expected character: '\'
SnippetAfterError: 015-02-26T11:29:36.000Z"
Stacktrace:    at _DynamicMethod21(TextReader , Int32 )
   at Jil.JSON.Deserialize[T](TextReader reader, Options options) in c:\Users\kanasra\Desktop\Jaguars\Jil Serilization\Jil-master\Jil\JSON.cs:line 971
   at Jil.JSON.Deserialize[T](String text, Options options) in c:\Users\kanasra\Desktop\Jaguars\Jil Serilization\Jil-master\Jil\JSON.cs:line 998
   at WebApiApp1.Controllers.ValuesController.Get() in c:\Users\kanasra\Documents\Visual Studio Projects\Asp.net Web Api\WebApiApp1\WebApiApp1\Controllers\ValuesController.cs:line 257

**Comment by kevin-montrose** [comment]
You have to specify the DateTimeFormat you want Jil to use, it defaults to Newtonsoft/Microsoft-style.

```
void Main()
{
	Employee obj = JSON.Deserialize<Employee>(@"{""joiningdate"":""2015-02-26T11:29:36.000Z""}", Options.ISO8601);
	obj.Dump();
}

class Employee
{
	public System.DateTimeOffset joiningdate { get; set; }
}
```

Does what you expect. `Options.ISO8601` is a convenience field, you can also construct an `Options` object manually.
