### ISSUE TITLE
Exception thrown when attempting to deserialize an object which contains an array of enum when the array gets to a certain arbitrary size

### ISSUE THREAD

**Issue by LeapingGorilla** [kevin-montrose/Jil#193]
An exception is thrown when attempting to deserialize an object which contains an array of enum when the array gets to a certain arbitrary size. The full stack trace is included below. A [simple console app is linked](https://media.leapinggorilla.com/Files/jilrepro.zip) which reproduces the issue (GitHub won't allow me to upload the Zip archive).

The type initializer for 'Jil.Deserialize.EnumLookup`1' threw an exception.
   at Jil.JSON.Deserialize[T](String text, Options options) in c:\Users\kevin_000\Dropbox\jil\Jil\JSON.cs:line 4819
   at JilRepro.Program.Main(String[] args) in c:\Sandbox\JilRepro\JilRepro\Program.cs:line 19
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   --   
   The type initializer for 'Jil.Deserialize.EnumLookup`1' threw an exception.
     at Jil.Deserialize.EnumLookup`1.GetEnumValueThunkReader(ThunkReader& reader)
     at _DynamicMethod2(ThunkReader& , Int32 )
     at Jil.JSON.Deserialize[T](String text, Options options) in c:\Users\kevin_000\Dropbox\jil\Jil\JSON.cs:line 4771
   
     --
     ""
         at Jil.Deserialize.NameAutomata`1.NextChar[V](Type readerType, Data`1 d, IList`1 nameValues, Int32 pos, Label onMatchChar) in c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 182
         at Jil.Deserialize.NameAutomata`1.NextChar[V](Type readerType, Data`1 d, IList`1 nameValues, Int32 pos, Label onMatchChar) in c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 229
         at Jil.Deserialize.NameAutomata`1.NextChar[V](Type readerType, Data`1 d, IList`1 nameValues, Int32 pos, Label onMatchChar) in c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 229
         at Jil.Deserialize.NameAutomata`1.NextChar[V](Type readerType, Data`1 d, IList`1 nameValues, Int32 pos, Label onMatchChar) in c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 229
         at Jil.Deserialize.NameAutomata`1.NextChar[V](Type readerType, Data`1 d, IList`1 nameValues, Int32 pos, Label onMatchChar) in c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 229
         at Jil.Deserialize.NameAutomata`1.CreateFold[DelegateType](Type readerType, IEnumerable`1 names, Action`1 initialize, Action`1 doReturn, Boolean skipWhitespace, Boolean foldMultipleValues, Boolean caseSensitive, Object defaultValue) in c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 438
         at Jil.Deserialize.NameAutomata`1.Create[DelegateType](Type readerType, IEnumerable`1 names, Boolean caseSensitive, Object defaultValue) in c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 450
         at Jil.Deserialize.EnumLookup`1.CreateFindEnum(IEnumerable`1 names) in c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\EnumLookup.cs:line 56
         at Jil.Deserialize.EnumLookup`1..cctor() in c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\EnumLookup.cs:line 26

**Comment by kevin-montrose** [comment]
The bug here is you set `T052 = 148`, a value which was also assigned to `T050`.  Jil should do a better job of reporting that error though, diggnig.

**Comment by kevin-montrose** [comment]
Hmm, thinking on this harder... for _enums_ that's probably shouldn't be an error at all.
