### ISSUE TITLE
Enum exception in 2.13.0 onwards

### ISSUE THREAD

**Issue by Fritzbraun** [kevin-montrose/Jil#225]
Hi there,

I'm having trouble deserializing enums in any version of Jil from 2.13 onwards. It works fine in 2.12.1. My code is pretty simple, it looks like this:

```
using System;
using System.Runtime.Serialization;
using Jil;

namespace JilTest
{
    [DataContract]
    public enum MyEnum
    {
        [EnumMember]
        Value0 = 0,
        [EnumMember]
        Value1 = 1
    }

    [DataContract]
    public class JilTest
    {
        [DataMember(Name = "PT")]
        public MyEnum PackagedType;
    }

    class Program
    {
        static void Main(string[] args)
        {
            var json = JSON.Serialize(new JilTest
            {
                PackagedType = MyEnum.Value0
            });

            var bean = JSON.Deserialize<JilTest>(json);
        }
    }
}
```
When this code is run I the serialization looks fine, but when it hits the deserialization I get this:

```
Jil.DeserializationException was unhandled
  EndedUnexpectedly=false
  HResult=-2146233088
  Message=The type initializer for 'Jil.Deserialize.EnumLookup`1' threw an exception.
  Source=Jil
  StackTrace:
       at Jil.JSON.Deserialize[T](String text, Options options) in C:\Users\kmontrose\Dropbox\jil\Jil\JSON.cs:line 4819
       at JilTest.Program.Main(String[] args) in c:\users\admin\documents\visual studio 2015\Projects\JilTest\JilTest\Program.cs:line 33
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233036
       Message=The type initializer for 'Jil.Deserialize.EnumLookup`1' threw an exception.
       Source=Jil
       TypeName=Jil.Deserialize.EnumLookup`1
       StackTrace:
            at Jil.Deserialize.EnumLookup`1.GetEnumValueThunkReader(ThunkReader& reader)
            at _DynamicMethod1(ThunkReader& , Int32 )
            at Jil.JSON.Deserialize[T](String text, Options options) in C:\Users\kmontrose\Dropbox\jil\Jil\JSON.cs:line 4771
       InnerException: 
            HResult=-2147467261
            Message=Object reference not set to an instance of an object.
            Source=Jil
            StackTrace:
                 at Jil.Deserialize.NameAutomata`1.<>c__DisplayClass5_0`1.<NextChar>b__0(AutomataName nv) in C:\Users\kmontrose\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 170
                 at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
                 at System.Linq.GroupedEnumerable`3.GetEnumerator()
                 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
                 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
                 at Jil.Deserialize.NameAutomata`1.NextChar[V](Type readerType, Data`1 d, IList`1 nameValues, Int32 pos, Label onMatchChar) in C:\Users\kmontrose\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 168
                 at Jil.Deserialize.NameAutomata`1.CreateFold[DelegateType](Type readerType, IEnumerable`1 names, Action`1 initialize, Action`1 doReturn, Boolean skipWhitespace, Boolean foldMultipleValues, Boolean caseSensitive, Object defaultValue) in C:\Users\kmontrose\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 441
                 at Jil.Deserialize.NameAutomata`1.Create[DelegateType](Type readerType, IEnumerable`1 names, Boolean caseSensitive, Object defaultValue) in C:\Users\kmontrose\Dropbox\jil\Jil\Deserialize\NameAutomata.cs:line 453
                 at Jil.Deserialize.EnumLookup`1.CreateFindEnum(IEnumerable`1 names) in C:\Users\kmontrose\Dropbox\jil\Jil\Deserialize\EnumLookup.cs:line 65
                 at Jil.Deserialize.EnumLookup`1..cctor() in C:\Users\kmontrose\Dropbox\jil\Jil\Deserialize\EnumLookup.cs:line 26
            InnerException: 
```
Any ideas of a workaround? I've rolled back to 2.12.1 for now, and that's working ok.

cheers,

Iain

**Comment by ectacoh** [comment]
It looks like when you set EnumMemberAttribute, Jil uses value from this attribute even if this value is null.
Simple additional check will do the trick.
I've replaced
if(enumMember != null)
with 
if(enumMember != null && null != enumMember.Value)
at row 48 of EnumLookups.cs
and now it works like a charm.
Hope this fix will be included in some future release.

**Comment by rrduarte** [comment]
I used the fix mention by @ectacoh and it worked. Would be possible to implement this? Actually I had to compile the code by myself to implement this.

Thanks
