### ISSUE TITLE
Exception when rendering structs which implement IEnumerable

### ISSUE THREAD

**Issue by benjamin-hodgson** [kevin-montrose/Jil#257]
My use case is rendering objects containing [`ImmutableArray`](https://msdn.microsoft.com/en-us/library/dn638264(v=vs.111).aspx)s, but here's a minimal repro:

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using Jil;

struct MyEnumerable : IEnumerable<object>
{
    public IEnumerator<object> GetEnumerator()
    {
        yield break;
    }
    IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
}

public class Program
{
    public static void Main(string[] args)
    {
        MyEnumerable enumerable = new MyEnumerable();
        var result = JSON.SerializeDynamic(enumerable);
        Console.WriteLine(result);
    }
}
```

This fails with an `AccessViolationException`:

```
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at _DynamicMethod0(ThunkWriter& , <>f__AnonymousType0`1 , Int32 )
   at Jil.JSON.Serialize[T](T data, Options options)
   at Program.Main(String[] args) in Program.cs:line 20
```

If I change `enumerable` to be typed as a _nullable_ `MyEnumerable`, I get a different exception:

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        MyEnumerable? enumerable = new MyEnumerable();
        var result = JSON.Serialize(enumerable);
        Console.WriteLine(result);
    }
}
```
```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at _DynamicMethod0(ThunkWriter& , <>f__AnonymousType0`1 , Int32 )
   at Jil.JSON.Serialize[T](T data, Options options)
   at Program.Main(String[] args) in Program.cs:line 20
```

If I change `enumerable` to be typed as an `IEnumerable<object>`, or if I make `MyEnumerable` into a `class` instead of a `struct`, I get no error and the code behaves correctly, outputting `[]` as expected.

I can reproduce this both in .NET 4.6 on Windows and .NET Core on OSX. I'm running the latest Jil (2.15.0).

**Comment by benjamin-hodgson** [comment]
Upon investigation, I think the bug is [here](https://github.com/kevin-montrose/Jil/blob/master/Jil/Serialize/InlineSerializer.cs#L2561-L2570). Comparing this to the IL the C# compiler generates for a `foreach` loop, it looks like we should be dispatching a `constrained` `callvirt` to the _address_ of the struct. I _think_ the code should look like this:

```csharp
if (enumerableType.IsValueType())
{
    if (inLocal != null)
    {
        Emit.LoadLocalAddress(inLocal);
    }
    else
    {
        Emit.LoadArgumentAddress(1);
    }
    Emit.CallVirtual(iEnumerableGetEnumerator, enumerableType);  // IEnumerator<>
}
else
{
    if (inLocal != null)
    {
        Emit.LoadLocal(inLocal);
    }
    else
    {
        Emit.LoadArgument(1);
    }
    Emit.CallVirtual(iEnumerableGetEnumerator);   // IEnumerator<>
}
```

I couldn't get this working because of [this Sigil issue](https://github.com/kevin-montrose/Sigil/issues/53).
