### ISSUE TITLE
Jil detected and infinite recursion and bailed

### ISSUE THREAD

**Issue by KRSatpute** [kevin-montrose/Jil#289]
**Getting Exception:**

**_Jil detected and infinite recursion and bailed_**
   at _DynamicMethod53(ThunkWriter& , DataViewManager , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at _DynamicMethod54(ThunkWriter& , DataView , Int32 )
   at _DynamicMethod55(ThunkWriter& , DataTable , Int32 )
   at Jil.JSON.Serialize[T](T data, Options options) in C:\Users\kmontrose\Dropbox\jil\Jil\JSON.cs:line 4592
   at DataAccessLayer.HelperUtils.DataTableToJson(DataTable dataTable) in D:\DataAccessUtility\DataAccessLayer\HelperUtils.cs:line 155
   at UnitTest.Program.Main(String[] args) in D:\DataAccessUtility\UnitTest\Program.cs:line 35

**Calling function:**
```
        /// <summary>
        /// Convert data table to json string.
        /// </summary>
        /// <returns>Indented json string.</returns>
        public static string DataTableToJson(DataTable dataTable)
        {
            return JSON.Serialize(dataTable, new Options(false, false, false, DateTimeFormat.ISO8601, true, UnspecifiedDateTimeKindBehavior.IsUTC, SerializationNameFormat.Verbatim));
        }
```

**Create DataTable like this:**

```
                var dt = new DataTable();

                dt.Columns.Add("DocumentTypeID", typeof(int));
                dt.Columns.Add("CmpanyEventTypeId", typeof(int));
                dt.Columns.Add("CompanyID", typeof(int));

                dt.Rows.Add(dt.NewRow());

                dt.Rows[0][0] = 1;
                dt.Rows[0][1] = 16;
                dt.Rows[0][2] = 20693;

                dt.Columns.Add("DocumentTypeID", typeof(int));
                dt.Columns.Add("CmpanyEventTypeId", typeof(int));
                dt.Columns.Add("CompanyID", typeof(int));

                dt.Rows.Add(dt.NewRow());

                dt.Rows[0][0] = 1;
                dt.Rows[0][1] = 16;
                dt.Rows[0][2] = 20693;
```

**Comment by KRSatpute** [comment]
Should this be happening for a DataTable with single row and three columns?

**Comment by kevin-montrose** [comment]
DataTable isn't really "plain" enough for direct serialization, at least for Jil.

Tabular data is best represented as an enumerable (like List<T> or T[]) of POCOs.

**Comment by sreekumarp** [comment]
> DataTable isn't really "plain" enough for direct serialization, at least for Jil.
> 
> Tabular data is best represented as an enumerable (like List or T[]) of POCOs.

But what if the column names are dynamic? => A Typical data from SQL Data Reader

**Comment by zissop** [comment]
So Jil can't serialize / deserialize DataSets? Great limitation if that's the case.
