### ISSUE TITLE
Use IncludeInherited option in serialize cause exception

### ISSUE THREAD

**Issue by binbit** [kevin-montrose/Jil#315]
While try to serialize an object that contains such property
`public IList<Expression<Func<AnotherClass, object>>> property { get; }`
get next exception

> System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
   at System.RuntimeType.get_GenericParameterPosition()
   at _DynamicMethod25(TextWriter , RuntimeType , Int32 )
   at Jil.SerializeDynamic.DynamicSerializer.SerializeInternal(MemberInfo dynamicMember, TextWriter stream, Object obj, Options opts, Int32 depth)
   at _DynamicMethod23(TextWriter , List`1 , Int32 )
   at Jil.SerializeDynamic.DynamicSerializer.SerializeInternal(MemberInfo dynamicMember, TextWriter stream, Object obj, Options opts, Int32 depth)
   at _DynamicMethod21(TextWriter , GetNextCollectionByCriteria , Int32 )
   at Jil.SerializeDynamic.DynamicSerializer.SerializeInternal(MemberInfo dynamicMember, TextWriter stream, Object obj, Options opts, Int32 depth)
   at Jil.JSON.SerializeDynamic(Object data, Options options)

**Comment by Wazner** [comment]
What output are you expecting from serialising an expression tree? Expression trees contain a lot of references and type information which cannot be serialised easily.
