### ISSUE TITLE
[Deserialization] Exception: `Expected digit`

### ISSUE THREAD

**Issue by Saibamen** [kevin-montrose/Jil#348]
This JSON can be deserialized by Newtonsoft.Json without any problems.

JSON:
```json
{
   "MyString":"testString",
   "MyInt":5,
   "MyIntButStringInJson":"234"
}
```

Class:
```csharp
public class TestJil
{
    public string MyString { get; set; }
    public int MyInt { get; set; }
    public int MyIntButStringInJson { get; set; }
}
```

Deserialization code:

```csharp
var testJson = "{\r\n   \"MyString\":\"testString\",\r\n   \"MyInt\":5,\r\n   \"MyIntButStringInJson\":\"234\"\r\n}";

using (var input = new StringReader(testJson))
{
    var dupaTam = JSON.Deserialize<TestJil>(input);
}
```

### Exception

`Message = "Expected digit"`

`SnippetAfterError = "234\"\r\n}"`

StackTrace:
```
at Jil.Deserialize.Methods._ReadInt32(TextReader reader)
at Jil.JSON.Deserialize[T](TextReader reader, Options options)
```

Jil version: **2.17.0**

**Comment by lettywang** [comment]
Hi, Do u have a solution now? I encountered the same problem. It's not easy to replace with other serialize lib base on my project.

**Comment by tcsaddul** [comment]
I think there is something wrong with your code. Make sure the int property gets an int value. It would be an optimization blow to JIL for detecting and converting a string to int.
